import { Router } from 'express';
import { createVideo, getVideosByCourse, createEvent, saveProgress, getVideoStats, updateVideoSettings, getAllCourses, createCourse, generateSubtitles, generateQuestions, resetVideoProgress, saveVideoProgress, getVideoProgress, reorderVideos, deleteVideo, updateCourse, deleteCourse, getUserVideoAnswers, updateCourseContentOrder, getCourseCollaborators, addCourseCollaborator, removeCourseCollaborator, transferCourseOwnership, applyForCourse, checkEnrollmentStatus, getCourseEnrollments, updateEnrollmentStatus, getCourseAnalytics, getStudentCourseDetails, getCourseItemAnalytics, generateDemoData, transcodeVideo, reTranscodeAllVideos, getMyEnrollments, getMyProgressAll, reorderCourses, banFromCourse, unbanFromCourse, getCourseBans, getTeacherAccessibleCourses, } from '../controllers/videoController.js';
import { checkCourseAccess, checkCourseBan } from '../middleware/courseAuthMiddleware.js';
import { checkAuth, checkAuthSse, demoRestrict } from '../middleware/authMiddleware.js';
import { validateId } from '../middleware/validateId.js';
import { updateEvent, deleteEvent, sseVideoEvents, sseEnrollStudentEvents, sseEnrollCourseEvents, sseSubtitleEvents } from '../controllers/videoController.js';
const router = Router();
const vId = validateId('videoId');
const cId = validateId('courseId');
const eId = validateId('eventId');
const enId = validateId('enrollmentId');
const sId = validateId('studentId');
const iId = validateId('itemId');
const uId = validateId('userId');
// --- СУЩЕСТВУЮЩИЕ РОУТЫ ---
router.get('/my-enrollments', checkAuth, getMyEnrollments);
router.get('/my-progress-all', checkAuth, getMyProgressAll);
router.get('/my-courses', checkAuth, getTeacherAccessibleCourses);
router.put('/reorder', checkAuth, demoRestrict, reorderVideos);
router.post('/:videoId/autocaptions', checkAuth, demoRestrict, vId, checkCourseAccess, generateSubtitles);
router.post('/:videoId/generate-questions', checkAuth, demoRestrict, vId, checkCourseAccess, generateQuestions);
router.post('/:videoId/transcode', checkAuth, demoRestrict, vId, checkCourseAccess, transcodeVideo);
router.post('/admin/retranscode-all', checkAuth, demoRestrict, reTranscodeAllVideos);
router.post('/', checkAuth, demoRestrict, createVideo);
router.get('/courses', checkAuth, getAllCourses);
router.post('/courses', checkAuth, demoRestrict, createCourse);
router.put('/courses/reorder', checkAuth, demoRestrict, reorderCourses);
router.put('/courses/:courseId', checkAuth, demoRestrict, cId, checkCourseAccess, updateCourse);
router.delete('/courses/:courseId', checkAuth, demoRestrict, cId, checkCourseAccess, deleteCourse);
router.get('/courses/:courseId/videos', checkAuth, cId, checkCourseBan, getVideosByCourse);
router.put('/courses/:courseId/transfer', checkAuth, demoRestrict, cId, checkCourseAccess, transferCourseOwnership);
router.post('/course/:courseId/reorder', checkAuth, demoRestrict, cId, checkCourseAccess, updateCourseContentOrder);
router.post('/courses/:courseId/enroll', checkAuth, cId, applyForCourse);
router.get('/courses/:courseId/enrollment-status', checkAuth, cId, checkEnrollmentStatus);
router.get('/courses/:courseId/collaborators', checkAuth, cId, getCourseCollaborators);
router.get('/courses/:courseId/enrollments', checkAuth, cId, checkCourseAccess, getCourseEnrollments);
router.get('/courses/:courseId/analytics', checkAuth, cId, checkCourseAccess, getCourseAnalytics);
router.get('/courses/:courseId/analytics/student/:studentId', checkAuth, cId, sId, checkCourseAccess, getStudentCourseDetails);
router.get('/courses/:courseId/analytics/item/:itemType/:itemId', checkAuth, cId, iId, checkCourseAccess, getCourseItemAnalytics);
router.post('/courses/:courseId/generate-demo', checkAuth, demoRestrict, cId, checkCourseAccess, generateDemoData);
router.put('/courses/enrollments/:enrollmentId', checkAuth, demoRestrict, enId, updateEnrollmentStatus);
router.post('/courses/:courseId/collaborators', checkAuth, demoRestrict, cId, checkCourseAccess, addCourseCollaborator);
router.delete('/courses/:courseId/collaborators/:userId', checkAuth, demoRestrict, cId, uId, checkCourseAccess, removeCourseCollaborator);
router.get('/courses/:courseId/bans', checkAuth, cId, checkCourseAccess, getCourseBans);
router.post('/courses/:courseId/bans/:userId', checkAuth, demoRestrict, cId, uId, checkCourseAccess, banFromCourse);
router.delete('/courses/:courseId/bans/:userId', checkAuth, demoRestrict, cId, uId, checkCourseAccess, unbanFromCourse);
// --- РОУТЫ ДЛЯ ТЕСТОВ (UserResponse) ---
router.post('/progress', checkAuth, saveProgress);
router.delete('/:videoId/progress', checkAuth, vId, resetVideoProgress);
router.get('/progress/:videoId', checkAuth, vId, getUserVideoAnswers);
router.get('/:videoId/stats', checkAuth, vId, checkCourseAccess, getVideoStats);
router.patch('/:videoId', checkAuth, demoRestrict, vId, checkCourseAccess, updateVideoSettings);
// --- НОВЫЕ РОУТЫ ДЛЯ ТАЙМЛАЙНА (UserVideoProgress) ---
router.get('/:videoId/playback-progress', checkAuth, vId, getVideoProgress);
router.post('/playback-progress', checkAuth, saveVideoProgress);
// --- ОСТАЛЬНОЕ ---
router.post('/:videoId/events', checkAuth, demoRestrict, vId, checkCourseAccess, createEvent);
router.put('/events/:eventId', checkAuth, demoRestrict, eId, checkCourseAccess, updateEvent);
router.delete('/events/:eventId', checkAuth, demoRestrict, eId, checkCourseAccess, deleteEvent);
router.delete('/:videoId', checkAuth, demoRestrict, vId, checkCourseAccess, deleteVideo);
// --- SSE-стримы ---
router.get('/:videoId/events/stream', checkAuthSse, vId, sseVideoEvents);
router.get('/enrollment/stream', checkAuthSse, sseEnrollStudentEvents);
router.get('/courses/:courseId/enrollment/stream', checkAuthSse, cId, sseEnrollCourseEvents);
router.get('/courses/:courseId/processing/stream', checkAuthSse, cId, sseSubtitleEvents);
export default router;
