const express = require('express');
const { execSync, spawn } = require('child_process');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const http = require('http');

const app = express();
const server = http.createServer(app);

app.use(express.json({ limit: '10mb' }));
app.use(express.static(path.join(__dirname, 'public')));

const WORKSPACE = process.env.WORKSPACE || '/workspace';
const STATE_FILE = path.join(WORKSPACE, '.lumeo_installer_state.json');
const DONE_FLAG = path.join(WORKSPACE, '.lumeo_installed');
const IMAGE_TAG = process.env.IMAGE_TAG || 'latest';
const GITHUB_OWNER = process.env.GITHUB_OWNER || 'banifacei';

// ─── State ────────────────────────────────────────────────────────────────────

let state = {
  step: 'check',       // check | config | admin | email | install | done
  config: {},
  admins: [],
  skippedSteps: [],
  generatedCredentials: null,
  installLog: [],
  installing: false,
  installed: fs.existsSync(DONE_FLAG),
};

function saveState() {
  try { fs.writeFileSync(STATE_FILE, JSON.stringify(state, null, 2)); } catch {}
}

if (fs.existsSync(STATE_FILE) && !state.installed) {
  try { Object.assign(state, JSON.parse(fs.readFileSync(STATE_FILE, 'utf8'))); } catch {}
}

// ─── SSE clients ──────────────────────────────────────────────────────────────

const logClients = new Set();

function pushLog(line) {
  state.installLog.push(line);
  for (const res of logClients) {
    res.write(`data: ${JSON.stringify(line)}\n\n`);
  }
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function generate(bytes = 32) {
  return crypto.randomBytes(bytes).toString('hex');
}

function checkSystem() {
  const results = [];

  try { execSync('docker --version', { stdio: 'pipe' }); results.push({ id: 'docker', ok: true, label: 'Docker', value: execSync('docker --version', { stdio: 'pipe' }).toString().trim() }); }
  catch { results.push({ id: 'docker', ok: false, label: 'Docker', value: 'Не найден — установите Docker' }); }

  try { execSync('docker compose version', { stdio: 'pipe' }); results.push({ id: 'compose', ok: true, label: 'Docker Compose', value: execSync('docker compose version', { stdio: 'pipe' }).toString().trim() }); }
  catch { results.push({ id: 'compose', ok: false, label: 'Docker Compose', value: 'Не найден — нужен Docker Compose v2' }); }

  try {
    const df = execSync('df -BG ' + WORKSPACE + ' | tail -1', { stdio: 'pipe' }).toString();
    const avail = parseInt(df.split(/\s+/)[3]);
    results.push({ id: 'disk', ok: avail >= 5, label: 'Свободное место', value: `${avail} ГБ доступно` + (avail < 5 ? ' (нужно минимум 5 ГБ)' : '') });
  } catch { results.push({ id: 'disk', ok: true, label: 'Свободное место', value: 'Не удалось проверить' }); }

  const ports = [80, 443, 5001];
  for (const port of ports) {
    try {
      execSync(`ss -tlnp | grep :${port}`, { stdio: 'pipe' });
      results.push({ id: `port${port}`, ok: false, label: `Порт ${port}`, value: `Занят — может быть конфликт` });
    } catch {
      results.push({ id: `port${port}`, ok: true, label: `Порт ${port}`, value: 'Свободен' });
    }
  }

  return results;
}

function writeEnv(config, admins, generatedCredentials) {
  const dbPassword = config.DB_PASSWORD || (generatedCredentials && generatedCredentials.DB_PASSWORD) || generate(16);
  const jwtSecret = config.JWT_SECRET || (generatedCredentials && generatedCredentials.JWT_SECRET) || generate(32);
  const adminPassword = (admins[0] && admins[0].password) || (generatedCredentials && generatedCredentials.ADMIN_PASSWORD) || generate(12);

  const lines = [
    `# Generated by LumeoLoadpad on ${new Date().toISOString()}`,
    '',
    `DB_NAME=${config.DB_NAME || 'lumeo_db'}`,
    `DB_USER=${config.DB_USER || 'lumeo'}`,
    `DB_PASSWORD=${dbPassword}`,
    `DB_HOST=postgres`,
    `DB_PORT=${config.DB_PORT || 5432}`,
    '',
    `JWT_SECRET=${jwtSecret}`,
    '',
    `CLIENT_URL=${config.CLIENT_URL || 'http://localhost'}`,
    `API_URL=${config.API_URL || 'http://localhost/api'}`,
    '',
    `ADMIN_EMAIL=${(admins[0] && admins[0].email) || 'admin@lumeo.local'}`,
    `ADMIN_PASSWORD=${adminPassword}`,
    `ADMIN_FIRST_NAME=${(admins[0] && admins[0].firstName) || 'Root'}`,
    `ADMIN_LAST_NAME=${(admins[0] && admins[0].lastName) || 'Admin'}`,
    '',
  ];

  if (config.SMTP_HOST) {
    lines.push(`SMTP_HOST=${config.SMTP_HOST}`);
    lines.push(`SMTP_PORT=${config.SMTP_PORT || 587}`);
    lines.push(`SMTP_USER=${config.SMTP_USER || ''}`);
    lines.push(`SMTP_PASS=${config.SMTP_PASS || ''}`);
    lines.push(`SMTP_FROM=${config.SMTP_FROM || config.SMTP_USER || ''}`);
    lines.push('');
  }

  lines.push(`LUMEO_INSTALLED=true`);

  fs.writeFileSync(path.join(WORKSPACE, '.env'), lines.join('\n'));
  return { dbPassword, jwtSecret, adminPassword };
}

function writeDockerCompose(config) {
  const owner = GITHUB_OWNER.toLowerCase();
  const tag = IMAGE_TAG;
  const exposePort = config.EXPOSE_PORT || 80;

  const content = `# Generated by LumeoLoadpad
services:
  postgres:
    image: postgres:15
    container_name: lumeo-postgres
    env_file: .env
    environment:
      POSTGRES_DB: \${DB_NAME}
      POSTGRES_USER: \${DB_USER}
      POSTGRES_PASSWORD: \${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \${DB_USER} -d \${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  server:
    image: ghcr.io/${owner}/lumeo-server:${tag}
    container_name: lumeo-server
    env_file: .env
    environment:
      DB_HOST: postgres
    volumes:
      - uploads:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "node -e \\"require('http').get('http://localhost:5001/api/theme',r=>process.exit(r.statusCode<500?0:1)).on('error',()=>process.exit(1))\\""]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 10s
    restart: unless-stopped

  client:
    image: ghcr.io/${owner}/lumeo-client:${tag}
    container_name: lumeo-client
    volumes:
      - uploads:/app/uploads:ro
    ports:
      - "${exposePort}:80"
    depends_on:
      server:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
  uploads:
`;

  fs.writeFileSync(path.join(WORKSPACE, 'docker-compose.yml'), content);
}

async function runInstall() {
  state.installing = true;
  state.installLog = [];
  saveState();

  try {
    pushLog({ type: 'info', text: '🚀 Начинаем установку Lumeo...' });

    // Генерация credentials если нужно
    const generated = {};
    if (!state.config.DB_PASSWORD) { generated.DB_PASSWORD = generate(16); pushLog({ type: 'warn', text: '🔑 DB_PASSWORD не задан — сгенерирован автоматически' }); }
    if (!state.config.JWT_SECRET) { generated.JWT_SECRET = generate(32); pushLog({ type: 'warn', text: '🔑 JWT_SECRET не задан — сгенерирован автоматически' }); }
    const firstAdmin = state.admins[0];
    if (firstAdmin && !firstAdmin.password) { generated.ADMIN_PASSWORD = generate(12); pushLog({ type: 'warn', text: '🔑 Пароль администратора не задан — сгенерирован автоматически' }); }

    const hasGenerated = Object.keys(generated).length > 0;
    if (hasGenerated) state.generatedCredentials = { ...generated };

    // Записываем .env
    pushLog({ type: 'info', text: '📝 Записываем .env...' });
    const { dbPassword, jwtSecret, adminPassword } = writeEnv(state.config, state.admins, generated);
    if (hasGenerated) {
      state.generatedCredentials.DB_PASSWORD = dbPassword;
      state.generatedCredentials.JWT_SECRET = jwtSecret;
      state.generatedCredentials.ADMIN_PASSWORD = adminPassword;
      state.generatedCredentials.ADMIN_EMAIL = (firstAdmin && firstAdmin.email) || 'admin@lumeo.local';
    }

    // Записываем docker-compose.yml
    pushLog({ type: 'info', text: '📝 Записываем docker-compose.yml...' });
    writeDockerCompose(state.config);

    // docker compose pull
    pushLog({ type: 'info', text: '📦 Скачиваем образы (это может занять несколько минут)...' });
    await runCommand('docker', ['compose', '-f', path.join(WORKSPACE, 'docker-compose.yml'), 'pull']);

    // docker compose up -d
    pushLog({ type: 'info', text: '▶️  Запускаем контейнеры...' });
    await runCommand('docker', ['compose', '-f', path.join(WORKSPACE, 'docker-compose.yml'), 'up', '-d']);

    // Ждём healthcheck сервера
    pushLog({ type: 'info', text: '⏳ Ждём готовности сервера...' });
    await waitForServer(state.config.CLIENT_URL || 'http://localhost', 60);

    // Создаём дополнительных администраторов (если были добавлены ещё)
    if (state.admins.length > 1) {
      pushLog({ type: 'info', text: '👤 Создаём дополнительных администраторов...' });
      for (const admin of state.admins.slice(1)) {
        await createExtraAdmin(admin);
      }
    }

    // Готово
    fs.writeFileSync(DONE_FLAG, new Date().toISOString());
    state.installed = true;
    state.step = 'done';
    state.installing = false;
    saveState();

    pushLog({ type: 'success', text: '✅ Lumeo успешно установлен!' });
    pushLog({ type: 'done', text: 'DONE' });

  } catch (err) {
    state.installing = false;
    saveState();
    pushLog({ type: 'error', text: `❌ Ошибка: ${err.message}` });
    pushLog({ type: 'failed', text: 'FAILED' });
  }
}

function runCommand(cmd, args) {
  return new Promise((resolve, reject) => {
    const proc = spawn(cmd, args, { cwd: WORKSPACE });
    proc.stdout.on('data', d => pushLog({ type: 'log', text: d.toString().trim() }));
    proc.stderr.on('data', d => pushLog({ type: 'log', text: d.toString().trim() }));
    proc.on('close', code => {
      if (code === 0) resolve();
      else reject(new Error(`${cmd} ${args.join(' ')} завершился с кодом ${code}`));
    });
  });
}

function waitForServer(baseUrl, maxAttempts) {
  return new Promise((resolve, reject) => {
    let attempts = 0;
    const url = baseUrl.replace(/\/$/, '') + '/api/theme';
    const check = () => {
      attempts++;
      const mod = url.startsWith('https') ? require('https') : require('http');
      const req = mod.get(url, (res) => {
        if (res.statusCode < 500) { pushLog({ type: 'info', text: `✅ Сервер отвечает (${res.statusCode})` }); resolve(); }
        else { retry(); }
      });
      req.on('error', () => retry());
      req.setTimeout(3000, () => { req.destroy(); retry(); });
    };
    const retry = () => {
      if (attempts >= maxAttempts) { reject(new Error('Сервер не поднялся за отведённое время')); return; }
      pushLog({ type: 'log', text: `⏳ Ожидание сервера... (${attempts}/${maxAttempts})` });
      setTimeout(check, 3000);
    };
    check();
  });
}

async function createExtraAdmin(admin) {
  // Дополнительные админы создаются через прямой вызов API после старта
  const baseUrl = state.config.CLIENT_URL || 'http://localhost';
  const payload = JSON.stringify({
    email: admin.email,
    password: admin.password || generate(12),
    firstName: admin.firstName,
    lastName: admin.lastName,
    role: 'admin',
    status: 'active',
  });
  return new Promise((resolve) => {
    const mod = baseUrl.startsWith('https') ? require('https') : require('http');
    const req = mod.request(baseUrl + '/api/setup/create-admin', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'Content-Length': payload.length, 'X-Setup-Token': state.config.JWT_SECRET || '' },
    }, () => resolve());
    req.on('error', () => resolve());
    req.write(payload);
    req.end();
  });
}

// ─── API Routes ───────────────────────────────────────────────────────────────

app.get('/api/state', (req, res) => {
  res.json({
    step: state.step,
    installed: state.installed,
    installing: state.installing,
    skippedSteps: state.skippedSteps,
    config: { ...state.config, DB_PASSWORD: state.config.DB_PASSWORD ? '***' : '', JWT_SECRET: state.config.JWT_SECRET ? '***' : '' },
    admins: state.admins.map(a => ({ ...a, password: a.password ? '***' : '' })),
  });
});

app.get('/api/system-check', (req, res) => {
  try { res.json({ ok: true, results: checkSystem() }); }
  catch (e) { res.json({ ok: false, error: e.message }); }
});

app.post('/api/config', (req, res) => {
  const { step, data } = req.body;
  if (step === 'config') state.config = { ...state.config, ...data };
  if (step === 'email') state.config = { ...state.config, ...data };
  if (step === 'admins') state.admins = data.admins || [];
  if (step === 'skip') state.skippedSteps.push(data.stepName);
  state.step = data.nextStep || state.step;
  saveState();
  res.json({ ok: true });
});

app.post('/api/install', (req, res) => {
  if (state.installing || state.installed) return res.json({ ok: false, reason: 'already_running' });
  runInstall();
  res.json({ ok: true });
});

app.get('/api/install-logs', (req, res) => {
  res.setHeader('Content-Type', 'text/event-stream');
  res.setHeader('Cache-Control', 'no-cache');
  res.setHeader('Connection', 'keep-alive');
  res.flushHeaders();

  // Отправляем накопленные логи
  for (const line of state.installLog) {
    res.write(`data: ${JSON.stringify(line)}\n\n`);
  }

  logClients.add(res);
  req.on('close', () => logClients.delete(res));
});

app.get('/api/credentials', (req, res) => {
  if (!state.installed) return res.status(403).json({ ok: false });
  res.json({ ok: true, credentials: state.generatedCredentials });
});

// Updater API (используется из adminpanel через Lumeo server proxy)
app.get('/api/check-updates', (req, res) => {
  if (!state.installed) return res.status(403).json({ ok: false });
  try {
    const current = execSync(`docker inspect --format='{{index .RepoDigests 0}}' lumeo-server 2>/dev/null || echo 'unknown'`, { stdio: 'pipe' }).toString().trim();
    res.json({ ok: true, current, latest: IMAGE_TAG });
  } catch {
    res.json({ ok: true, current: 'unknown', latest: IMAGE_TAG });
  }
});

app.post('/api/update', (req, res) => {
  if (!state.installed) return res.status(403).json({ ok: false });
  res.json({ ok: true });
  (async () => {
    state.installLog = [];
    pushLog({ type: 'info', text: '🔄 Начинаем обновление Lumeo...' });
    try {
      await runCommand('docker', ['compose', '-f', path.join(WORKSPACE, 'docker-compose.yml'), 'pull']);
      await runCommand('docker', ['compose', '-f', path.join(WORKSPACE, 'docker-compose.yml'), 'up', '-d', '--no-deps', 'server', 'client']);
      pushLog({ type: 'success', text: '✅ Обновление завершено!' });
      pushLog({ type: 'done', text: 'DONE' });
    } catch (err) {
      pushLog({ type: 'error', text: `❌ Ошибка обновления: ${err.message}` });
      pushLog({ type: 'failed', text: 'FAILED' });
    }
  })();
});

app.get('/api/update-logs', (req, res) => {
  res.setHeader('Content-Type', 'text/event-stream');
  res.setHeader('Cache-Control', 'no-cache');
  res.setHeader('Connection', 'keep-alive');
  res.flushHeaders();
  for (const line of state.installLog) res.write(`data: ${JSON.stringify(line)}\n\n`);
  logClients.add(res);
  req.on('close', () => logClients.delete(res));
});

// Heartbeat
setInterval(() => {
  for (const res of logClients) res.write(': heartbeat\n\n');
}, 15000);

// ─── Start ────────────────────────────────────────────────────────────────────

const PORT = process.env.PORT || 3333;
server.listen(PORT, '0.0.0.0', () => {
  console.log(`\n🚀 LumeoLoadpad запущен на http://0.0.0.0:${PORT}`);
  if (state.installed) {
    console.log('✅ Lumeo уже установлен — работает в режиме Updater');
  } else {
    console.log('📋 Откройте http://SERVER_IP:3333 для настройки');
  }
});
